'use client';
import {useState} from 'react';
import {Bell,CalendarPlus} from 'lucide-react';
import {reminderCalendar,type Reminder} from '@/lib/reminders';
import type {Program} from '@/lib/policy/engine';
import {translate,type Language} from '@/lib/i18n';
const localInput=(at?:string)=>{if(!at)return '';const d=new Date(at);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export function ReminderEditor({program,reminder,language,busy,onSave}:{program:Program;reminder?:Reminder;language:Language;busy:boolean;onSave:(at:string|null)=>Promise<boolean>}){
 const [value,setValue]=useState(()=>localInput(reminder?.at));const [error,setError]=useState('');const t=(s:string)=>translate(s,language);
 async function save(){const d=new Date(value);if(!value||!Number.isFinite(d.getTime())||d.getTime()<=Date.now()){setError(t('Choose a future date and time.'));return;}if(await onSave(d.toISOString()))setError('');}
 function download(){if(!reminder)return;const url=URL.createObjectURL(new Blob([reminderCalendar(program,reminder.at,language)],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`aidpath-${program.id}-reminder.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="reminder-editor" aria-label={t('Deadline reminder')}><div className="reminder-heading"><Bell size={18}/><strong>{t('A nudge for your next step')}</strong></div><p>{t('Pick your own follow-up date. This is not an official program deadline.')}</p><div className="reminder-controls"><label htmlFor={`reminder-${program.id}`}>{t('Date and time')}<input id={`reminder-${program.id}`} type="datetime-local" value={value} onChange={e=>setValue(e.target.value)} disabled={busy}/></label><button className="secondary" disabled={busy||!value} onClick={()=>void save()}>{t(reminder?'Update reminder':'Save reminder')}</button></div><p className="small">{t('Uses your device’s time zone.')}</p>{error&&<p role="alert">{error}</p>}{reminder&&<div className="reminder-saved"><p><strong>{t(Date.parse(reminder.at)<Date.now()?'Due for follow-up':'Reminder saved')}</strong> · {new Date(reminder.at).toLocaleString(language==='es'?'es-MX':'en-US')}</p><div className="reminder-buttons"><button className="primary" onClick={download}><CalendarPlus size={16}/>{t('Add to calendar')}</button><button className="text-button" disabled={busy} onClick={async()=>{if(await onSave(null)){setValue('');setError('');}}}>{t('Remove reminder')}</button></div><p className="small">{t('Import the downloaded calendar file and allow alerts in your calendar app. AidPath does not send email or push notifications. Removing this reminder does not remove an imported calendar event.')}</p></div>}</section>;
}
