import catalog from '../data/programs.json';
import {db} from './db';
import {rank,type Answers,type Program} from './policy/engine';
import {nextQuestion,questions,needs} from './policy/questions';
export const programs=catalog as Program[];
export async function seed(){const d=db();const cutoff=Date.now()-30*86400000;await d.batch([d.prepare('DELETE FROM events WHERE created_at<?').bind(cutoff),d.prepare('DELETE FROM sessions WHERE updated_at<?').bind(cutoff),d.prepare('DELETE FROM failures WHERE created_at<?').bind(cutoff)]);await d.batch(programs.flatMap(p=>[d.prepare('INSERT OR IGNORE INTO policy_versions (id,program_id,version,payload,created_at) VALUES (?,?,?,?,?)').bind(`${p.id}:${p.policy_version}`,p.id,p.policy_version,JSON.stringify(p),p.retrieved_at),d.prepare('INSERT OR IGNORE INTO sources (url,hash,status,checked_at) VALUES (?,?,?,?)').bind(p.source_url,p.source_hash,p.review_status,p.retrieved_at)]));}
export async function currentPrograms(){await seed();const rows=await db().prepare('SELECT * FROM sources').all<{url:string;hash:string;status:string;checked_at:string}>();const approvals=await db().prepare('SELECT * FROM policy_approvals').all<{id:string;source_hash:string}>();return programs.map(p=>{const s=rows.results.find(s=>s.url===p.source_url);const approved=approvals.results.some(a=>a.id===`${p.id}:${p.policy_version}`&&a.source_hash===p.source_hash);return {...p,policy_review_status:approved?'APPROVED':'DRAFT',review_status:s?.hash!==p.source_hash?'REVIEW_REQUIRED':s?.status??'UNAVAILABLE',retrieved_at:s?.status==='SOURCE_CHECKED'?s.checked_at:p.retrieved_at};});}
export async function savedProgram(item:SavedPlan){const row=await db().prepare('SELECT payload FROM policy_versions WHERE id=?').bind(`${item.id}:${item.version}`).first<{payload:string}>();return row?JSON.parse(row.payload) as Program:null;}
export type SavedPlan={id:string;version:string;checked:number[];reminder?:{at:string}};
export type Session={id:string;revision:number;answers:string;plan:string;created_at:number;updated_at:number};
export async function event(session:string,name:string,program:string|null=null,value:number|null=null){await db().prepare('INSERT INTO events (id,session_id,name,program_id,value,created_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),session,name,program,value,Date.now()).run();}
export async function state(s:Session){const a=JSON.parse(s.answers) as Answers;const list=await currentPrograms();const saved=JSON.parse(s.plan) as SavedPlan[];const plan=await Promise.all(saved.map(async item=>({...item,program:await savedProgram(item)})));const complete=!!a.need&&!nextQuestion(a);const recommended=complete?rank(list,a):[];const preview=complete?rank(list.filter(p=>p.policy_review_status!=='APPROVED'),a,new Date(),{preview:true}):[];return {revision:s.revision,answers:a,plan,programs:list,recommendations:recommended,previewRecommendations:preview,question:a.need?nextQuestion(a):null,totalQuestions:questions(a).length,answeredQuestions:questions(a).filter(q=>a[q.field]!==undefined).length};}
export {nextQuestion,questions,needs};
