import json,urllib.request,re,hashlib,datetime,concurrent.futures,pathlib
base='https://basicneeds.berkeley.edu'
overview=base+'/about-us/services-and-resources';fund=base+'/get-support/finances/emergency-fund'
def rule(field,value,label,op='equals',kind='policy',required=True):return dict(field=field,operator=op,value=value,required=required,label=label,kind=kind)
enrolled=rule('enrolled','yes','Current Berkeley enrollment')
emergency=[enrolled,rule('exhausted','yes','Available financial resources exhausted'),rule('recent_award','no','No emergency fund award in the past two years'),rule('unexpected','yes','Unexpected or emergency expense')]
def p(id,name,categories,summary,url,rules,steps,documents=[],caveat='Staff make the final decision; support and availability are not guaranteed.',priority=5,urgent=False):
 return dict(id=id,name=name,category=categories,summary=summary,source_url=url,rules=rules,steps=steps,documents=documents,caveat=caveat,priority=priority,urgent=urgent,effective_date=None,policy_version='2026-10-01.1',review_status='SOURCE_CHECKED')
def route(f,v,label):return rule(f,v,label,kind='routing')
programs=[
p('pantry','Basic Needs Food Pantry',['food'],'Free groceries for short-term food needs.',base+'/pantry',[enrolled],['Check current pantry hours and complete the student profile form linked on the official page.','Join the virtual line, or ask for help at the check-in table.','Bring your Cal ID or number and a bag.'],['Cal ID or Cal ID number'],'Visits are limited to once per week. Hours and closures can change.',9,True),
p('calfresh','CalFresh application assistance',['food'],'Help exploring ongoing food benefits and applying.',base+'/calfresh',[enrolled],['Review the official eligibility guidance and prescreener.','Book application help with a CalFresh ambassador.','Use the official application guide to prepare documents.'],[],'AidPath recommends application assistance, not CalFresh eligibility. Additional income, student, and status rules apply.',7),
p('meals','Grab n Go meals',['food'],'Prepared recovered meals when donations are available.',base+'/get-support/food/food-recovery',[enrolled],['Check today’s availability and access details on the official page.','Visit the Welcome Center or an eligible partner space.'],[],'Meal availability and variety are not guaranteed.',8,True),
p('emergency-housing','Emergency housing',['housing'],'Short-term help for students without safe housing.',base+'/get-support/housing/emergency-housing',[enrolled,route('housing_type','unsafe','No safe housing or imminent housing loss'),rule('unexpected','yes','Unplanned housing emergency'),rule('exhausted','yes','No resources for alternative housing')],['Open the official page and complete the assistance form.','Explain your housing urgency directly to the Basic Needs team.','If the office is closed, use the after-hours resources on that page.'],[],'Extremely limited availability. Planned gap housing is excluded. The program is not a 24-hour service.',10,True),
p('rent','Emergency fund: rent support',['housing'], 'A rent-assistance pathway within the Basic Needs Emergency Fund.',fund,emergency+[route('housing_type','rent','Help with rent')],['Review the fund requirements and response timeline.','Ask staff what supporting information your situation requires.','Complete the assistance form linked on the official page.'],[],'One fund, not a separate award. Responses may take 7–10 weekdays; support is not guaranteed.',10),
p('deposit','Emergency fund: housing deposit',['housing'],'Deposit assistance through the same emergency fund.',fund,emergency+[route('housing_type','deposit','Help with a housing deposit')],['Review fund requirements.','Prepare a copy of your lease agreement.','Complete the official assistance form.'],['Lease agreement'],'Part of the Basic Needs Emergency Fund; do not assume multiple awards.',9),
p('food-award','Emergency fund: food assistance',['food'],'Food-cost support when the pantry is not sufficient.',fund,emergency+[route('food_type','award','Food needs beyond pantry support'),rule('food_exception','yes','Additional CalFresh or extenuating-circumstance conditions require staff review')],['Review the food-specific criteria on the official page.','Discuss the CalFresh or exceptional-circumstance requirements with staff.','Use the official assistance form.'],[],'This is an emergency-fund pathway. Additional food-specific conditions remain unconfirmed.',8),
p('emergency-fund','Basic Needs Emergency Fund',['financial'],'One-time help for unanticipated basic-needs expenses.',fund,emergency,['Read the full requirements and timeline.','Confirm documentation with the Basic Needs team.','Submit the official assistance form.'],[],'A response can take 7–10 weekdays. Meeting published criteria does not guarantee funding.',10),
p('housing-search','Housing search resources',['housing'],'Self-guided resources for finding housing.',base+'/get-support/housing/housing-search-support',[route('housing_type','search','Looking for housing')],['Open the housing search resource guide.','Compare on-campus housing and Cal Rentals options.'],[],'The Basic Needs team says it cannot provide direct housing-search support.',8),
p('tenant','Tenant-rights resources',['housing'],'Official referrals for landlord and tenant concerns.',base+'/get-support/housing/tenants-rights-other-resources',[route('housing_type','legal','A landlord or tenant-rights issue')],['Review the legal-service options on the official page.','Contact the appropriate service about your situation and deadlines.'],[],'This is a referral directory, not legal advice. Each provider has its own intake requirements.',9),
p('dsp-tech','DSP Student Technology Grant',['technology'],'Funding consideration for disability-related assistive equipment.','https://dsp.berkeley.edu/financial-aid',[enrolled,rule('disability','yes','Disability-related assistive technology need'),rule('fafsa','yes','FAFSA completed')],['Review the technology grant information on the DSP page.','Contact your DSP specialist about equipment needs and the application.'],[],'This grant is not emergency funding. The award is limited to assistive technology.',9),
p('financial-wellness','Financial wellness counseling',['financial'],'Financial-aid guidance and prevention-focused support.',overview,[enrolled],['Review financial wellness services.','Ask the Basic Needs Center about financial-aid counseling opportunities.'],[],'Counseling is not a promise of emergency funding.',4)
]
programs.extend([
p('loan','Short-term emergency loan',['financial'],'An education-related emergency loan that must be repaid.','https://financialaid.berkeley.edu/types-of-aid-at-berkeley/loans/short-term-emergency-loan/',[enrolled,rule('loan_conditions','yes','Registration, holds, debt and loan-type conditions require official review')],['Review the applicable loan type, repayment deadline and terms.','Ask Cal Student Central about any restrictions before borrowing.','If appropriate, apply through the official CalCentral instructions.'],[],'This is debt, not a grant. Approval is not guaranteed; review generally takes 2–3 business days. Verify current repayment terms.',3),
p('eop','Educational Opportunity Program',['financial'],'Counseling and campus referrals for students navigating barriers.','https://eop.berkeley.edu/',[enrolled,rule('eop_scope','yes','EOP participant scope needs confirmation with staff')],['Review EOP services and participant information.','Schedule an appointment to discuss support and referrals.'],[],'A counseling referral, not a funding decision. Ask EOP whether its services fit your circumstances.',2),
p('scholarships','OURS scholarship advising',['financial'],'Explore competitive scholarships and fellowships for future planning.','https://scholarships.berkeley.edu/',[enrolled,rule('undergraduate_scope','yes','Undergraduate or recent undergraduate alumni scope needs confirmation')],['Review scholarship opportunities and their deadlines.','Contact the OURS office for advising.'],[],'Not emergency funding. Each scholarship has its own requirements and selection process.',1)
])
def fetch(url):
 req=urllib.request.Request(url,headers={'User-Agent':'AidPath-source-check/1.0'})
 html=urllib.request.urlopen(req,timeout=30).read().decode('utf-8')
 text=re.sub(r'<script\b[^>]*>[\s\S]*?</script>','',html,flags=re.I)
 text=re.sub(r'<style\b[^>]*>[\s\S]*?</style>','',text,flags=re.I)
 text=re.sub(r'<!--[\s\S]*?-->','',text);text=re.sub(r'<[^>]+>',' ',text);text=re.sub(r'\s+',' ',text).strip()
 h=hashlib.sha256(text.encode()).hexdigest();pathlib.Path('data/sources/'+h+'.txt').write_text(text)
 return url,dict(source_hash=h,retrieved_at=datetime.datetime.now(datetime.timezone.utc).isoformat())
with concurrent.futures.ThreadPoolExecutor(max_workers=8) as ex:sources=dict(ex.map(fetch,sorted(set(p['source_url'] for p in programs))))
for p in programs:p.update(sources[p['source_url']])
pathlib.Path('data/programs.json').write_text(json.dumps(programs,indent=2))
print(f'Saved {len(programs)} resources across {len(sources)} retrieved official pages')
